import asyncio
import dataclasses


@dataclasses.dataclass
class StepOutput:
    """
    The output of one decoding step
    """
    token_id: int
    request: "Request"


class RawRequest:
    """
    A request issued by user
    """
    prompt: str
    max_tokens: int
    ignore_eos: bool

    def __init__(self, prompt: str, max_tokens: int, ignore_eos: bool = False):
        self.prompt = prompt
        self.max_tokens = max_tokens
        self.ignore_eos = ignore_eos


class Request:
    """
    A (queuing, processing, or finished) request in the system
    """

    prompt_token_ids: list[int]     # Prompt token ids, generated by the tokenizer upon request arrival
    prompt_len: int     # len(prompt_token_ids)
    max_tokens: int     # Max number of generated tokens
    ignore_eos: bool
    finish_reason: str | None

    output_q: asyncio.Queue[StepOutput] # Queue initialized when the raw request enters the
                                        # engine, and to be set upon a new token being generated
                                        # Mainly for streaming the output back to the user
    finished_event: asyncio.Event       # Event to be set when the request is finished
                                        # Mainly for the non-streaming case

    request_id: int     # Request ID, within range [0, max_seqs_in_block_table).
                        # Generated before being prefilled, and used as the index
                        # into the block table
    output_token_ids: list[int]     # Output token ids

    def __init__(self, raw_request: RawRequest):
        # A request is __init__-ed when entering `untokenized_raw_requests`, and
        # its `prompt_token_ids` and `prompt_len` will be set upon tokenization
        self.prompt_token_ids = []
        self.prompt_len = 0
        self.max_tokens = raw_request.max_tokens
        self.ignore_eos = raw_request.ignore_eos
        self.finish_reason = None
        self.output_q = asyncio.Queue()
        self.finished_event = asyncio.Event()
        self.request_id = -1
        self.output_token_ids = []

    def maybe_mark_finished(self, token_id: int, eos_token_id: int | None) -> None:
        if self.finish_reason is not None:
            return
        if len(self.output_token_ids) >= self.max_tokens:
            self.finish_reason = "max_tokens"
            return
        if not self.ignore_eos and eos_token_id is not None and token_id == eos_token_id:
            self.finish_reason = "eos"

    def is_finished(self) -> bool:
        return self.finish_reason is not None

    def get_cur_output_len(self) -> int:
        return len(self.output_token_ids)

    def is_prefill_stage(self) -> bool:
        return not self.output_token_ids
